### ISSUE TITLE
Feature Request - Changing the diff preview to show diffs of individual commits, rather than cumulative

### ISSUE THREAD

**Issue by ColinKennedy** [dawsers/telescope-file-history.nvim#3]
Hiya, I tried out this plug-in to replace one I'd made and I'm really enjoying it except I'm not much value out of the diff view at the moment and wanted to explain why. If you're open to it, I have a suggestion that I think could be added as a separate configuration option or maybe a different history view, separate from the current one that exists, so people can use what they prefer.

## Demo
https://github.com/dawsers/telescope-file-history.nvim/assets/10103049/2d2a0268-7e9c-493c-b2a5-02b997701465

## Summary / Suggestion
It seems that the diff preview shows a sort of hybrid reverse view of each commit and compares it to the current buffer. Could we get a different diff preview option where it shows each file save and the contents changed per-save?

## Explanation
In the recording I start with a brand new file with some existing newlines and one line of text and then add 3 newlines.

If you look at the diff, the entry that says `1 second ago` is showing the beginning of the git history (nothing), and then the `2 minutes ago` commit shows the lines that I'd added **as deleted lines** and not as added lines as expected. Then I change a line and the `1 second ago` is still showing the beginning of the git history and the `X ago` are the latest histories. And somehow the second commit shows the "changed line" text even though it doesn't have that change yet because that was in the latest commit.

To compare / contrast the git diff between what gets written into `~/.file-history-git` vs what the plug-in shows.

### `~/.file-history-git`
`git diff HEAD^..HEAD`
```diff
@@ -6,7 +6,7 @@



-blah2221zzz
+blah2221zzz changed line
```

### telescope-file-history.nvim 
(Technically the view claims this is the oldest commit, not the latest)
```diff
@@ -6,7 +6,4 @@



-blah2221zzz changed line
-
-
-
+blah2221zzz
```

### `~/.file-history-git`
`git diff HEAD^^..HEAD^`
```diff
@@ -7,3 +7,7 @@
 
 
 blah2221zzz
+
+
+
+
```

### telescope-file-history.nvim 
```diff
@@ -6,7 +6,8 @@



-blah2221zzz changed line
+blah2221zzz
+
```

I think I understand the intent behind the preview. This is supposed to show "this is what your file could look like if you reverted back to this commit" and the "newest" history is actually the current definition of the file and "older" history is rewinding which is why added lines appear as `-` rather than `+` like I would've intuited.

Personally though I'd get a lot more value out of this plug-in if it shows the changes done between the current save and the previous save. It maps better IMO ("I added 10 lines here - oh, now I see, I added those lines during this save") vs currently it's the opposite "I added 10 lines here. But to find the save I have to look between two commits that both show the added lines as `-` and mentally diff the two commits to infer what I actually added during this save). It's a lot more mental work by comparison to do the same task.

Anyway, all this to say, I'd love an option to change the preview display to be by-save (commit) rather than cumulative. What do you think?

**Comment by ColinKennedy** [comment]
Update: I edited the code to get what I was expecting over at https://github.com/ColinKennedy/telescope-file-history.nvim/tree/combined_branch. However it is WIP because commands like `<M-d>` still diff the old contents (for example). I could make it real and PR it in here, if interested.

https://github.com/dawsers/telescope-file-history.nvim/assets/10103049/d140968c-dbe9-4094-829c-b34669874b6b

**Comment by dawsers** [comment]
I understand your point of view. If you are looking for a typical git diff plugin, the way telescope-file-history does things is not intuitive. The philosophy behind it is to recover work that is lost and was there earlier. That is why it works the opposite way and is not incremental. A repository wants to store jobs, in many cases by different people, so they can be manipulated atomically. telescope-file-history just tries to show you at all times the difference of the state of your older work with what you have now, so if you decide to open that version of the file, you know what you will get (what will change globally). I could add a new mode to get incremental changes from the history of the file, in fact it is simpler than what it does, as it would just require to get the commit information from the git repo, but Telescope wouldn't show something meaningful with respect to the file you are editing, the changes would be related to the different snapshots shown by Telescope, so the "preview" wouldn't really be a preview.  Still, when you open that older version of the file in a diff view, you would see what you are seeing now.

I am not opposed to adding this, I just don't think it should be default. Let me have a look at it during the weekend.

Thank you for taking the time to use and analyze the plugin.

**Comment by dawsers** [comment]
I added the option to preview the incremental changes created with each save in [this](https://github.com/dawsers/telescope-file-history.nvim/commit/0f8dab459f7b76a95d77d2f1d9b16446a97af62e) commit. You can use this option either through the new command `Telescope file_history log` or by adding the `log=true` option to `history`, as in `Telescope file_history history log=true`.
